In [1]:
import numpy as np
import pandas as pd


In [2]:
met=np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
met

array([[200, 220, 250],
       [ 68,  79, 105],
       [110, 140, 180],
       [ 80,  85,  90]])

### Dot product in numpy

In [4]:
np.dot(75,met)


array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [24]:
sold=np.array([[50,60,25],[10,13,5],[40,70,52]])
price_per_unit=np.array([20,30,15])



In [25]:
sold

array([[50, 60, 25],
       [10, 13,  5],
       [40, 70, 52]])

In [26]:
price_per_unit

array([20, 30, 15])

In [27]:
np.dot(price_per_unit,sold)

array([1900, 2640, 1430])